MONGODB_HOST: mongodb.divyavutakanti.shop
REDIS_HOST: redis.divyavutakanti.shop
CATALOGUE_HOST: catalogue.divyavutakanti.shop
CART_HOST: cart.divyavutakanti.shop
USER_HOST: user.divyavutakanti.shop
RABBITMQ_HOST: rabbitmq.daws86s.shop
MYSQL_HOST: mysql.divyavutakanti.shop
SHIPPING_HOST: shipping.divyavutakanti.shop
PAYMENT_HOST: payment.divyavutakanti.shop