
$ANSIBLE_VAULT;1.1;AES256
39363435613965333536393936653761626366623033656365376338626230653465626637363538
6338313265663363393561346132663938373735633638360a626334393931343738323866323164
34646466396330313639636436393835353961643538323663383237666666363638623864333038
6463633138336638380a396530393838326563343033663734646432316463666232373432663039
34306635306332363038333834323934386361616261363733353039633235313062346138306230
3831383931613235663234363438363530643537383031633566