#  MYSQL_ROOT_PASSWORD: ! vault | 
#   $ANSIBLE_VAULT;1.1;AES256
#   34633638383633656464316537373434356466373864656639663837316438643630326137663035
#   3039376639386432376434636462336565663530633733650a336536386237386564363839343261
#   33303332353137356430656237383632353530303732636264313535376632353661613634336465
#   6134326166326461630a363332363430613531333166623637653566616564666137353662383065
#   61323935376132346236623430363865373131613832643938633438356563643563323431353038
#   6437373033373662643861333564653133353733323735306438