- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup-tasks

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml














# catalogue is one role, common is another role
# catalogue should import the tasks in common role
# ansible.builtin.import_role: