- name: disable default node js module
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable module nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: install dependencies
  community.general.npm:
    path: /app
  tags:
  - deployment